name: Deploy GoClaw to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            cd /opt/goclaw
            
            # Update source code from GitHub
            git pull origin main
            
            # Make sure VERSION file is updated
            make version-file
            
            # Recreate and start docker-compose services
            docker compose -f docker-compose.yml -f docker-compose.postgres.yml up -d --pull always
            
            # Run upgrade and migrations
            docker compose -f docker-compose.yml -f docker-compose.postgres.yml -f docker-compose.upgrade.yml run --rm upgrade
            
            # Cleanup unused docker images to save space
            docker image prune -f
